module.exports = {
  title: 'Tipify (DamengRandom)',
  themeConfig: {
    nav: [
      { text: 'Github', link: 'https://github.com/DamengRandom/tipify' }
    ],
    sidebar: [
      'tipify.html',
      'git-tips-one.html',
      'react-tips-one.html',
      'js-reduce-method.html',
      'ts-basics.html',
      'dotnet-basics.html',
      'js-high-order-functions.html',
      'js-callback-promise-async-await.html',
      'js-general-tips.html',
      'js-event-loop.html',
      'js-hoisting.html',
      'js-closure.html',
      'dotnet-cqrs.html',
      'react-hoc.html',
      'server-side-rendering.html',
      'react-lifecycle.html',
      'js-immutability.html',
      'react-hooks-tips.html',
      'one-word-tips.html',
      'weekly-tips.html',
      'css-bem.html',
      'js-module-systems.html',
      'vuex-terms.html',
      'docker-basics.html',
      'vuejs-tips.html',
      './postgres-tips.html',
      'sql-tips.html',
      'webpack-tips.html',
      'redux-tips.html',
      'errors-I-saw.html',
      'css-tips.html',
      'tips-to-read.html',
      'tricky-js-recalls.html',
      'node-tips.html',
      'npms.html',
      'restful-api.html',
      'concepts.html'
    ],
    searchMaxSuggestions: 20
  },
  dest: 'public',
  port: 5151,
  serviceWorker: true
};
